---
swagger: "2.0"
info:
  description: |-
    This API cound crack passwords that matches the regular expression [A-Za-z0-9?!]{1,3} and encrypted using SHA-1 or SHA-256. This decrypter can quickly find the corresponding password in the lookup table with a time complexity of O(1). But it only cracks unsalted hashes.
    
    Some useful links:
    - [The MicroDecrypter repository](https://github.com/Danlinlin/MicroDecrypter)
    - [The source API definition for the MicroDecrypter](https://github.com/Danlinlin/MicroDecrypter/blob/main/swagger.yaml)
  version: "1.0.1"
  title: "Swagger CrackStation"
host: "do5prfdoyl.execute-api.us-east-1.amazonaws.com"
basePath: "/prod"
schemes:
- "https"
tags:
  - name: decrypter
    description: "A tool that can crack hashes."
paths:
  /password/{shaHash}:
    get:
      tags:
        - decrypter
      produces:
      - "application/json"
      parameters:
      - name: "shaHash"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful return password"
          schema:
            $ref: "#/definitions/Success"
        "404":
          description: "Hash not found"
          schema:
            $ref: "#/definitions/Failure"
definitions:
  Success:
    type: "object"
    title: "Success Schema"
    example: 
        {"f62e2ae559db0107b0a5b1f597441d0af709b3a807eb3e4f98f5e05ef2774177" : "?6a"}
  Failure:
    type: "object"
    title: "Failure Schema"
    example: 
        {"asdfjslakdjflkssdf177" : "Password not found"}